---
- name: Fluentd | Stop fluent service
  service:
    name: td-agent
    state: stopped

- name: Fluentd | Purge td-agent
  apt:
    name: td-agent
    state: absent
    autoremove: true
    clean: true
    purge: true

- name: Fluentd | Remove lines containing 'td-agent' from dpkg statoverride
  lineinfile:
    path: /var/lib/dpkg/statoverride
    regexp: '^.*td-agent.*$'
    state: absent
  backup: yes

- name: Fluentd | Remove td-agent user
  user:
    name: td-agent
    state: absent
    remove: yes

- name: Fluentd | Remove old conf file
  file:
    state: absent 
    path: /etc/fluent/td-agent.conf
  when: fluentd_del_old_conf | bool

- name: Fluentd | Remove repo
  apt_repository:
    repo: deb http://packages.treasuredata.com/4/ubuntu/{{ ansible_distribution_release|string }}/ {{ ansible_distribution_release|string }} contrib
    state: absent
