---
- name: Fluentd | Download Fluentd apt-source package
  ansible.builtin.get_url:
    url: https://packages.treasuredata.com/lts/5/ubuntu/{{ ansible_distribution_release|string }}/pool/contrib/f/fluent-lts-apt-source/fluent-lts-apt-source_2023.7.29-1_all.deb
    dest: /tmp/fluent-apt-source.deb

- name: Fluentd | Install Fluentd apt-source package
  ansible.builtin.apt:
    deb: /tmp/fluent-apt-source.deb
    state: present

- name: Fluentd | Install Fluentd package
  ansible.builtin.apt:
    update_cache: yes
    name: fluent-package
    state: present
  notify:
    - Check Fluentd Configuration

- name: Fluentd | Register plugins list
  command: "fluent-gem list"
  register: plugins_list
  changed_when: false
  
- name: Fluentd | Add the user fluentd to systemd-journal adm,syslog group
  user:
    name:  _fluentd
    groups: systemd-journal,adm,syslog
    append: yes
  tags: user

- name: Fluentd | Install fluentd plugins
  command: "fluent-gem install {{ item }}"
  with_items: "{{ fluentd_plugins }}"
  when: not item in plugins_list.stdout

- name: Fluentd | Create fluentd directory for side files
  file:
    path: /var/lib/fluentd
    owner: "_fluentd"
    group: "_fluentd"
    mode: 0755
    state: directory

- name: Fluentd | Check if the directory for ssl exists
  stat:
    path: "{{ ssl_directory_path }}/{{ domain_directory }}"
  register: dir_stat

- name: Fluentd | Find certs in the directory
  find:
    paths: "{{ ssl_directory_path }}/{{ domain_directory }}"
    patterns: "*.pem"
  when: dir_stat.stat.exists
  register: cert_files

- name: Fluentd | Set 644 permissions for certs
  file:
    path: "{{ item.path }}"
    mode: '0644'
  loop: "{{ cert_files.files }}"
  when: dir_stat.stat.exists

- name: Fluentd | Set 755 permissions for the directory
  file:
    path: "{{ ssl_directory_path }}/{{ domain_directory }}"
    mode: '0755'
  when: dir_stat.stat.exists
