---
- name: Fluentd | Install repo apt key
  apt_key:
    url: https://packages.treasuredata.com/GPG-KEY-td-agent
    state: present

- name: Fluentd | Add repository
  apt_repository:
    repo: deb http://packages.treasuredata.com/4/ubuntu/{{ ansible_distribution_release|string }}/ {{ ansible_distribution_release|string }} contrib
    state: present

- name: Fluentd | Install fluentd
  apt:
    update_cache: yes
    name: "td-agent"
    state: present
  notify:
    - Restart Fluentd

- name: Fluentd | Register plugins list
  command: "td-agent-gem list"
  register: plugins_list
  changed_when: false
  
- name: Add the user td-agent to systemd-journal adm,syslog group
  user:
    name:  td-agent
    groups: systemd-journal,adm,syslog
    append: yes
  tags: user

- name: Fluentd | Install fluentd plugins
  command: "td-agent-gem install {{ item }}"
  with_items: "{{ fluentd_plugins }}"
  when: not item in plugins_list.stdout

- name: Fluentd | Create fluentd directory for side files
  file:
    path: /var/lib/fluentd
    owner: "td-agent"
    group: "td-agent"
    mode: 0755
    state: directory
