---
- name: Fluentd | Stop fluent service
  service:
    name: td-agent
    state: stopped
  when: fluentd_migrate_to_v5 | bool

- name: Fluentd | Install repo apt key
  apt_key:
    url: https://packages.treasuredata.com/GPG-KEY-fluent-package
    state: present

- name: Fluentd | Add repository
  apt_repository:
    repo: deb http://packages.treasuredata.com/lts/5/ubuntu/{{ ansible_distribution_release|string }}/ {{ ansible_distribution_release|string }} contrib
    state: present

- name: Fluentd | Install fluentd
  apt:
    update_cache: yes
    name: "fluent-package"
    state: present
  notify:
    - Restart Fluentd

- name: Fluentd | Register plugins list
  command: "fluent-gem list"
  register: plugins_list
  changed_when: false
  
- name: Fluentd | Add the user td-agent to systemd-journal adm,syslog group
  user:
    name:  _fluentd
    groups: systemd-journal,adm,syslog
    append: yes
  tags: user

- name: Fluentd | Install fluentd plugins
  command: "fluent-gem install {{ item }}"
  with_items: "{{ fluentd_plugins }}"
  when: not item in plugins_list.stdout

- name: Fluentd | Create fluentd directory for side files
  file:
    path: /var/lib/fluentd
    owner: "_fluentd"
    group: "_fluentd"
    mode: 0755
    state: directory
