---
- name: Fluentd | Stop fluent service
  service:
    name: td-agent
    state: stopped
  when: fluentd_migrate_to_v5 | bool

- name: Fluentd | Install repo apt key
  apt_key:
    url: https://packages.treasuredata.com/GPG-KEY-fluent-package
    state: present

- name: Fluentd | Add repository
  apt_repository:
    repo: deb http://packages.treasuredata.com/lts/5/ubuntu/{{ ansible_distribution_release|string }}/ {{ ansible_distribution_release|string }} contrib
    state: present

- name: Fluentd | Install fluentd
  apt:
    update_cache: yes
    name: "fluent-package"
    state: present
  notify:
    - Restart Fluentd

- name: Fluentd | Register plugins list
  command: "fluent-gem list"
  register: plugins_list
  changed_when: false
  
- name: Fluentd | Add the user td-agent to systemd-journal adm,syslog group
  user:
    name:  fluentd
    groups: systemd-journal,adm,syslog
    append: yes
  tags: user

- name: Fluentd | Install fluentd plugins
  command: "fluent-gem install {{ item }}"
  with_items: "{{ fluentd_plugins }}"
  when: not item in plugins_list.stdout

- name: Fluentd | Create fluentd directory for side files
  file:
    path: /var/lib/fluentd
    owner: "fluentd"
    group: "fluentd"
    mode: 0755
    state: directory

- name: Fluentd | Check if the directory for ssl exists
  stat:
    path: "{{ ssl_directory_path }}/{{ domen_directory }}"
  register: dir_stat

- name: Fluentd | Find certs in the directory
  find:
    paths: "{{ ssl_directory_path }}/{{ domen_directory }}"
    patterns: "*.pem"
  when: dir_stat.stat.exists
  register: cert_files

- name: Fluentd | Set 644 permissions for certs
  file:
    path: "{{ item.path }}"
    mode: '0644'
  loop: "{{ cert_files.files }}"
  when: dir_stat.stat.exists

- name: Fluentd | Set 755 permissions for the directory
  file:
    path: "{{ ssl_directory_path }}/{{ domen_directory }}"
    mode: '0755'
  when: dir_stat.stat.exists
